docker run -dit \
  -p "$INPUT_BOT_HTTP_PORT":"$INPUT_BOT_HTTP_PORT" \
  -e APP_ENV="$INPUT_APP_ENV" \
  -e APP_DEBUG=true \
  -e APP_HOST=0.0.0.0 \
  -e APP_PORT="$INPUT_BOT_HTTP_PORT" \
  -e DISCORD_BOT_TOKEN="$INPUT_DISCORD_BOT_TOKEN" \
  -e DISCORD_PULL_REQUEST_CHANNEL_ID="$INPUT_DISCORD_PULL_REQUEST_CHANNEL_ID" \
  -e UPTIME_CHANNEL_ID="$INPUT_UPTIME_CHANNEL_ID" \
  -e UPTIME_WEBSITE_URL="$INPUT_UPTIME_WEBSITE_URL" \
  -e UPTIME_CHECK_INTERVAL="$INPUT_UPTIME_CHECK_INTERVAL" \
  -e UPTIME_ALERT_MESSAGE="$INPUT_UPTIME_ALERT_MESSAGE" \
  -e GITHUB_WEBHOOK_SECRET="$INPUT_GITHUB_WEBHOOK_SECRET" \
  -e DISCORD_CORE_ROLE_ID="$INPUT_DISCORD_CORE_ROLE_ID" \
  --network "$INPUT_APP_ENV" \
  --network-alias discord-bot-"$INPUT_APP_NAME" \
  --name discord-bot-"$INPUT_APP_ENV"-"$INPUT_APP_NAME" \
  "$INPUT_IMAGE"
